### ISSUE TITLE
User should be able to search for an article

### ISSUE THREAD

**Issue by lytes20** [ramani-io/ramani-blog#1]
Business/User Value:_ As a User, I would like to be able to search for an article by using keywords, title, or author

## Acceptance Criteria
**GIVEN** A user 
**WHEN** User navigates to the article landing page
**THEN** User should see a search bar where they can enter text to search for an articl

## DEV NOTES
A user should be able to enter text in an input and search 

## DESIGN Notes
See image mockup below 👇🏿 
<img width="709" alt="Screenshot 2023-10-09 at 00 25 35" src="https://github.com/ramani-io/ramani-blog/assets/25790450/9fb60ebc-a4bb-49bd-a4fa-dc06b19fa0aa">

**Comment by bryanguillen** [comment]
Hello, @lytes20 .  I can take a look at this one, if that's alright with you.

**Comment by lytes20** [comment]
@bryanguillen please feel free to take this one.  And thank you for taking this on

**Comment by bryanguillen** [comment]
Hey @lytes20 , excellent!  I'll get to work on this.

Quick follow-up: Is there a slack channel or some sort of other instant messaging channel for the project?  If not totally fine, but curious for collaboration purposes.

**Comment by lytes20** [comment]
@bryanguillen thank you for asking about an instant messaging channel. I have just created one. Please use this [link](https://join.slack.com/t/ramanixhacktoberfest/shared_invite/zt-24l21gt3r-QuyMqqyXB3gE4Lkm4LhiCA) to join the workspace:

**Comment by bryanguillen** [comment]
@lytes20 , cool, joined!  Looking forward to collaborating and sharing real time updates there.

**Comment by lytes20** [comment]
Search bar component has been added in this [PR](https://github.com/ramani-io/ramani-blog/pull/14)
Closing the issue now
